create table if not exists categories
(
    id bigint generated by default as identity constraint "categories_pk" primary key,
    category varchar not null unique
);

alter table categories owner to postgres;

create table if not exists roles
(
    id bigserial primary key,
    role varchar not null unique
);

alter table roles owner to postgres;

create table if not exists users
(
    id bigserial primary key,
    email varchar not null unique,
    username varchar not null unique,
    pass      varchar              not null,
    r_id bigint not null constraint users_roles_id_fk references roles,
    is_active boolean default true not null
);

alter table users owner to postgres;

create table if not exists cu
(
    c_id bigint not null
        constraint cu_categories_id_fk
            references categories
            on delete cascade,
    u_id bigint not null
        constraint cu_users_id_fk
            references users
            on delete cascade
);

alter table cu owner to postgres;

