create table if not exists news."Category"
(
    id bigint generated by default as identity constraint "Category_pk" primary key,
    category varchar not null unique
);

alter table news."Category" owner to postgres;

create table if not exists news."Role"
(
    id bigserial primary key,
    role varchar not null unique
);

alter table news."Role" owner to postgres;

create table if not exists news."User"
(
    id bigserial primary key,
    email varchar not null unique,
    username varchar not null unique,
    pass      varchar              not null,
    r_id bigint not null constraint user_role_id_fk references news."Role",
    is_active boolean default true not null
);

alter table news."User" owner to postgres;

create table if not exists news."CU"
(
    c_id bigint not null
        constraint cu_category_id_fk
            references news."Category"
            on delete cascade,
    u_id bigint not null
        constraint cu_user_id_fk
            references news."User"
            on delete cascade
);

alter table news."CU" owner to postgres;

